import json
import os

import run_warehub


def main():
    body = '\n'.join(
        (
            f'## 🟢 New package registration form',
            f'',
            f'- **Repository:** Mimer29or40/pythonnet-stubs',
            f'- **Domain:** ',
            f'- **Username:** ',
            f'- **Password:** ',
        )
    )

    os.environ['GITHUB_CONTEXT'] = json.dumps(
        {
            'token':             '***',
            'job':               'build',
            'ref':               'refs/heads/master',
            'sha':               '1378e0facd4f67e85b0eb98468efea6d74300f70',
            'repository':        'Mimer29or40/GithubPyPI',
            'repository_owner':  'Mimer29or40',
            'repositoryUrl':     'git://github.com/Mimer29or40/GithubPyPI.git',
            'run_id':            '1730458460',
            'run_number':        '3',
            'retention_days':    '90',
            'run_attempt':       '1',
            'actor':             'Mimer29or40',
            'workflow':          'warehub',
            'head_ref':          '',
            'base_ref':          '',
            'event_name':        'issues',
            'event':             {
                'action':     'edited',
                'changes':    {
                    'body': {
                        'from': '## 🟢 New package registration form\r\n\r\n- **Package name :** Test Issue\r\n- **Version :** 1.2.3.4\r\n- **Author :** Me\r\n- **Short '
                                'description '
                                ':** A sample package\r\n- **Long description :** A longer description of a sample package\r\n```html\r\n\r\n```\r\n- **Homepage :** '
                                'https://www.homepage.com/\r\n- **Link :** https://www.homepage.com/\r\n'
                    }
                },
                'issue':      {
                    'active_lock_reason':       None,
                    'assignee':                 None,
                    'assignees':                [],
                    'author_association':       'OWNER',
                    'body':                     body,
                    'closed_at':                None,
                    'comments':                 0,
                    'comments_url':             'https://api.github.com/repos/Mimer29or40/GithubPyPI/issues/1/comments',
                    'created_at':               '2022-01-21T19:02:09Z',
                    'events_url':               'https://api.github.com/repos/Mimer29or40/GithubPyPI/issues/1/events',
                    'html_url':                 'https://github.com/Mimer29or40/GithubPyPI/issues/1',
                    'id':                       1110793540,
                    'labels':                   [],
                    'labels_url':               'https://api.github.com/repos/Mimer29or40/GithubPyPI/issues/1/labels{/name}',
                    'locked':                   False,
                    'milestone':                None,
                    'node_id':                  'I_kwDOGtt9785CNV1E',
                    'number':                   1,
                    'performed_via_github_app': None,
                    'reactions':                {
                        '+1':          0,
                        '-1':          0,
                        'confused':    0,
                        'eyes':        0,
                        'heart':       0,
                        'hooray':      0,
                        'laugh':       0,
                        'rocket':      0,
                        'total_count': 0,
                        'url':         'https://api.github.com/repos/Mimer29or40/GithubPyPI/issues/1/reactions'
                    },
                    'repository_url':           'https://api.github.com/repos/Mimer29or40/GithubPyPI',
                    'state':                    'open',
                    'timeline_url':             'https://api.github.com/repos/Mimer29or40/GithubPyPI/issues/1/timeline',
                    'title':                    '🟢 New package: Test Issue',
                    'updated_at':               '2022-01-21T19:38:19Z',
                    'url':                      'https://api.github.com/repos/Mimer29or40/GithubPyPI/issues/1',
                    'user':                     {
                        'avatar_url':          'https://avatars.githubusercontent.com/u/7897914?v=4',
                        'events_url':          'https://api.github.com/users/Mimer29or40/events{/privacy}',
                        'followers_url':       'https://api.github.com/users/Mimer29or40/followers',
                        'following_url':       'https://api.github.com/users/Mimer29or40/following{/other_user}',
                        'gists_url':           'https://api.github.com/users/Mimer29or40/gists{/gist_id}',
                        'gravatar_id':         '',
                        'html_url':            'https://github.com/Mimer29or40',
                        'id':                  7897914,
                        'login':               'Mimer29or40',
                        'node_id':             'MDQ6VXNlcjc4OTc5MTQ=',
                        'organizations_url':   'https://api.github.com/users/Mimer29or40/orgs',
                        'received_events_url': 'https://api.github.com/users/Mimer29or40/received_events',
                        'repos_url':           'https://api.github.com/users/Mimer29or40/repos',
                        'site_admin':          False,
                        'starred_url':         'https://api.github.com/users/Mimer29or40/starred{/owner}{/repo}',
                        'subscriptions_url':   'https://api.github.com/users/Mimer29or40/subscriptions',
                        'type':                'User',
                        'url':                 'https://api.github.com/users/Mimer29or40'
                    }
                },
                'repository': {
                    'allow_forking':     True,
                    'archive_url':       'https://api.github.com/repos/Mimer29or40/GithubPyPI/{archive_format}{/ref}',
                    'archived':          False,
                    'assignees_url':     'https://api.github.com/repos/Mimer29or40/GithubPyPI/assignees{/user}',
                    'blobs_url':         'https://api.github.com/repos/Mimer29or40/GithubPyPI/git/blobs{/sha}',
                    'branches_url':      'https://api.github.com/repos/Mimer29or40/GithubPyPI/branches{/branch}',
                    'clone_url':         'https://github.com/Mimer29or40/GithubPyPI.git',
                    'collaborators_url': 'https://api.github.com/repos/Mimer29or40/GithubPyPI/collaborators{/collaborator}',
                    'comments_url':      'https://api.github.com/repos/Mimer29or40/GithubPyPI/comments{/number}',
                    'commits_url':       'https://api.github.com/repos/Mimer29or40/GithubPyPI/commits{/sha}',
                    'compare_url':       'https://api.github.com/repos/Mimer29or40/GithubPyPI/compare/{base}...{head}',
                    'contents_url':      'https://api.github.com/repos/Mimer29or40/GithubPyPI/contents/{+path}',
                    'contributors_url':  'https://api.github.com/repos/Mimer29or40/GithubPyPI/contributors',
                    'created_at':        '2022-01-21T18:04:22Z',
                    'default_branch':    'master',
                    'deployments_url':   'https://api.github.com/repos/Mimer29or40/GithubPyPI/deployments',
                    'description':       'A github hosted pypi server using github actions',
                    'disabled':          False,
                    'downloads_url':     'https://api.github.com/repos/Mimer29or40/GithubPyPI/downloads',
                    'events_url':        'https://api.github.com/repos/Mimer29or40/GithubPyPI/events',
                    'fork':              False,
                    'forks':             0,
                    'forks_count':       0,
                    'forks_url':         'https://api.github.com/repos/Mimer29or40/GithubPyPI/forks',
                    'full_name':         'Mimer29or40/GithubPyPI',
                    'git_commits_url':   'https://api.github.com/repos/Mimer29or40/GithubPyPI/git/commits{/sha}',
                    'git_refs_url':      'https://api.github.com/repos/Mimer29or40/GithubPyPI/git/refs{/sha}',
                    'git_tags_url':      'https://api.github.com/repos/Mimer29or40/GithubPyPI/git/tags{/sha}',
                    'git_url':           'git://github.com/Mimer29or40/GithubPyPI.git',
                    'has_downloads':     True,
                    'has_issues':        True,
                    'has_pages':         False,
                    'has_projects':      False,
                    'has_wiki':          False,
                    'homepage':          None,
                    'hooks_url':         'https://api.github.com/repos/Mimer29or40/GithubPyPI/hooks',
                    'html_url':          'https://github.com/Mimer29or40/GithubPyPI',
                    'id':                450592239,
                    'is_template':       False,
                    'issue_comment_url': 'https://api.github.com/repos/Mimer29or40/GithubPyPI/issues/comments{/number}',
                    'issue_events_url':  'https://api.github.com/repos/Mimer29or40/GithubPyPI/issues/events{/number}',
                    'issues_url':        'https://api.github.com/repos/Mimer29or40/GithubPyPI/issues{/number}',
                    'keys_url':          'https://api.github.com/repos/Mimer29or40/GithubPyPI/keys{/key_id}',
                    'labels_url':        'https://api.github.com/repos/Mimer29or40/GithubPyPI/labels{/name}',
                    'language':          'Python',
                    'languages_url':     'https://api.github.com/repos/Mimer29or40/GithubPyPI/languages',
                    'license':           None,
                    'merges_url':        'https://api.github.com/repos/Mimer29or40/GithubPyPI/merges',
                    'milestones_url':    'https://api.github.com/repos/Mimer29or40/GithubPyPI/milestones{/number}',
                    'mirror_url':        None,
                    'name':              'GithubPyPI',
                    'node_id':           'R_kgDOGtt97w',
                    'notifications_url': 'https://api.github.com/repos/Mimer29or40/GithubPyPI/notifications{?since,all,participating}',
                    'open_issues':       1,
                    'open_issues_count': 1,
                    'owner':             {
                        'avatar_url':          'https://avatars.githubusercontent.com/u/7897914?v=4',
                        'events_url':          'https://api.github.com/users/Mimer29or40/events{/privacy}',
                        'followers_url':       'https://api.github.com/users/Mimer29or40/followers',
                        'following_url':       'https://api.github.com/users/Mimer29or40/following{/other_user}',
                        'gists_url':           'https://api.github.com/users/Mimer29or40/gists{/gist_id}',
                        'gravatar_id':         '',
                        'html_url':            'https://github.com/Mimer29or40',
                        'id':                  7897914,
                        'login':               'Mimer29or40',
                        'node_id':             'MDQ6VXNlcjc4OTc5MTQ=',
                        'organizations_url':   'https://api.github.com/users/Mimer29or40/orgs',
                        'received_events_url': 'https://api.github.com/users/Mimer29or40/received_events',
                        'repos_url':           'https://api.github.com/users/Mimer29or40/repos',
                        'site_admin':          False,
                        'starred_url':         'https://api.github.com/users/Mimer29or40/starred{/owner}{/repo}',
                        'subscriptions_url':   'https://api.github.com/users/Mimer29or40/subscriptions',
                        'type':                'User',
                        'url':                 'https://api.github.com/users/Mimer29or40'
                    },
                    'private':           False,
                    'pulls_url':         'https://api.github.com/repos/Mimer29or40/GithubPyPI/pulls{/number}',
                    'pushed_at':         '2022-01-21T18:58:25Z',
                    'releases_url':      'https://api.github.com/repos/Mimer29or40/GithubPyPI/releases{/id}',
                    'size':              8,
                    'ssh_url':           'git@github.com:Mimer29or40/GithubPyPI.git',
                    'stargazers_count':  0,
                    'stargazers_url':    'https://api.github.com/repos/Mimer29or40/GithubPyPI/stargazers',
                    'statuses_url':      'https://api.github.com/repos/Mimer29or40/GithubPyPI/statuses/{sha}',
                    'subscribers_url':   'https://api.github.com/repos/Mimer29or40/GithubPyPI/subscribers',
                    'subscription_url':  'https://api.github.com/repos/Mimer29or40/GithubPyPI/subscription',
                    'svn_url':           'https://github.com/Mimer29or40/GithubPyPI',
                    'tags_url':          'https://api.github.com/repos/Mimer29or40/GithubPyPI/tags',
                    'teams_url':         'https://api.github.com/repos/Mimer29or40/GithubPyPI/teams',
                    'topics':            [],
                    'trees_url':         'https://api.github.com/repos/Mimer29or40/GithubPyPI/git/trees{/sha}',
                    'updated_at':        '2022-01-21T18:48:27Z',
                    'url':               'https://api.github.com/repos/Mimer29or40/GithubPyPI',
                    'visibility':        'public',
                    'watchers':          0,
                    'watchers_count':    0
                },
                'sender':     {
                    'avatar_url':          'https://avatars.githubusercontent.com/u/7897914?v=4',
                    'events_url':          'https://api.github.com/users/Mimer29or40/events{/privacy}',
                    'followers_url':       'https://api.github.com/users/Mimer29or40/followers',
                    'following_url':       'https://api.github.com/users/Mimer29or40/following{/other_user}',
                    'gists_url':           'https://api.github.com/users/Mimer29or40/gists{/gist_id}',
                    'gravatar_id':         '',
                    'html_url':            'https://github.com/Mimer29or40',
                    'id':                  7897914,
                    'login':               'Mimer29or40',
                    'node_id':             'MDQ6VXNlcjc4OTc5MTQ=',
                    'organizations_url':   'https://api.github.com/users/Mimer29or40/orgs',
                    'received_events_url': 'https://api.github.com/users/Mimer29or40/received_events',
                    'repos_url':           'https://api.github.com/users/Mimer29or40/repos',
                    'site_admin':          False,
                    'starred_url':         'https://api.github.com/users/Mimer29or40/starred{/owner}{/repo}',
                    'subscriptions_url':   'https://api.github.com/users/Mimer29or40/subscriptions',
                    'type':                'User',
                    'url':                 'https://api.github.com/users/Mimer29or40'
                }
            },
            'server_url':        'https://github.com',
            'api_url':           'https://api.github.com',
            'graphql_url':       'https://api.github.com/graphql',
            'ref_name':          'master',
            'ref_protected':     False,
            'ref_type':          'branch',
            'secret_source':     'Actions',
            'workspace':         '/home/runner/work/GithubPyPI/GithubPyPI',
            'action':            '__run',
            'event_path':        '/home/runner/work/_temp/_github_workflow/event.json',
            'action_repository': 'actions/setup-python',
            'action_ref':        'v2.3.1',
            'path':              '/home/runner/work/_temp/_runner_file_commands/add_path_893b60c4-41ef-4706-b164-757d79107652',
            'env':               '/home/runner/work/_temp/_runner_file_commands/set_env_893b60c4-41ef-4706-b164-757d79107652'
        }
    )

    run_warehub.main()


if __name__ == '__main__':
    main()
